[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["debug","tokio"] }
tokio = { version = "1.38.0", features = ["fs", "full", "rt"] }
